drivers: net: cnss2: Fix unused-function errors
Clang shows:

../drivers/net/wireless/cnss2/main.c:2024:14: error: unused function 'cnss_create_ramdump_device' [-Werror,-Wunused-function]
static void *cnss_create_ramdump_device(struct cnss_plat_data *plat_priv)
             ^
../drivers/net/wireless/cnss2/main.c:2032:13: error: unused function 'cnss_destroy_ramdump_device' [-Werror,-Wunused-function]
static void cnss_destroy_ramdump_device(struct cnss_plat_data *plat_priv,
            ^
2 errors generated.

Signed-off-by: atndko <z1281552865@gmail.com>
Signed-off-by: Jyotiraditya Panda <jyotiraditya@aospa.co>